# base-files version 4.2-3
# ~/.bashrc: executed by bash(1) for interactive shells.

# The latest version as installed by the Cygwin Setup program can
# always be found at /etc/defaults/etc/skel/.bashrc

# Modifying /etc/skel/.bashrc directly will prevent
# setup from updating it.

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# Don't wait for job termination notification
set -o notify

# Don't use ^D to exit
set -o ignoreeof

# Use case-insensitive filename globbing
shopt -s nocaseglob

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell

# Completion options
# These completion tuning parameters change the default behavior of bash_completion:
#
# Uncomment to turn on programmable completion enhancements.
# Any completions you add in ~/.bash_completion are sourced last.
[[ -f /etc/bash_completion ]] && . /etc/bash_completion

# History Options
# Don't put duplicate lines in the history.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups

# Umask
# /etc/profile sets 022, removing write perms to group + others.
# Set a more restrictive umask: i.e. no exec perms for others:
# umask 027
# Paranoid: neither group nor others have any perms:
# umask 077

# Always set the drive prefix to just /, not "/cygdrive"
# This has now been configured in /etc/fstab, so no need to do it here
#mount --change-cygdrive-prefix /

# Ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of patterns which should be excluded.
# The '&' is a special pattern which suppresses duplicate entries.
# export HISTIGNORE=$'[ \t]*:&:[fb]g:exit'
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls:la:ll:h' # Ignore the ls command as well

#
# Whenever displaying the prompt, write the previous line to disk
# export PROMPT_COMMAND="history -a"

# Functions
if [ -f "${HOME}/aliases/bash/functions" ]; then
   source "${HOME}/aliases/bash/functions"
fi

# Aliases
if [ -f "${HOME}/aliases/bash/aliases" ]; then
   source "${HOME}/aliases/bash/aliases"
fi

# Set the command prompt
# The first version sets the xterm title too
#PS1="\[\e]0;\w\a\]\[\e[32m\]\h \[\e[33m\]\w\[\e[0m\]> "
PS1="\[\e[32m\]\h \[\e[33m\]\w\[\e[0m\]> "

# Allow CNTRL+V pasting
stty lnext ^q stop undef start undef
