# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.

alias_dir=~/aliases/bash
alias via="vi $alias_dir/bash_aliases"
alias vib='vi ~/.bashrc'
alias vif='vi $alias_dir/bash_functions'
alias src='source ~/.bashrc'

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# Misc :)
alias less='less -r'                          # raw control characters
alias more=less
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour

# Some shortcuts for different directory listings
alias ls='ls -hF --color=tty'                 # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'
alias la='ls -lA'
alias l='ls -CF'                              #
alias h=history

# Visual Studio and Build aliases
# Allow a different standard path for devenv.exe
if [ -z "$DEVENV_ROOT" ]; then
  export DEVENV_ROOT="C:/Program Files (x86)"
fi

export defArchCSharp="AnyCPU"
if [ "$defCompiler" == "VS2008" ]; then
  export defArchCSharp=$defArch
fi
